name: Test
on: 
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2


      - name: Install & Test 🧪
        run: npm install && npm run test

      - name: Build 🔧
        run: mv organizations.js src/organizations.js
